<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\StockFlow.DataAccess\StockFlow.DataAccess.csproj" />
    <ProjectReference Include="..\StockFlow.Entities\StockFlow.Entities.csproj" />
  </ItemGroup>

</Project>
